CREATE TABLE ADDRESS
(
    ADDRESS_ID UUID PRIMARY KEY,
    ADDRESS VARCHAR(70)
);
CREATE TABLE ADDRESS_TYPE
(
    ADDRESS_TYPE_ID UUID PRIMARY KEY,
    ADDRESS_NAME VARCHAR(50)
);
CREATE TABLE CONTACT_TYPE
(
    CONTACT_TYPE_ID UUID PRIMARY KEY,
    CONTACT_NAME VARCHAR(50)
);
CREATE TABLE DOCUMENT_TYPE
(
    DOCUMENT_TYPE_ID UUID PRIMARY KEY,
    DOCUMENT_NAME VARCHAR(50)
);
CREATE TABLE PERSON
(
    PERSON_ID UUID PRIMARY KEY,
    FULL_NAME VARCHAR(100),
    BIRTH_DAY DATE
);
CREATE TABLE PERSON_ADDRESS
(
    PERSON_ADDRESS_ID UUID PRIMARY KEY,
    ADDRESS_ID UUID REFERENCES ADDRESS(ADDRESS_ID),
    ADDRESS_TYPE_ID UUID REFERENCES ADDRESS_TYPE(ADDRESS_TYPE_ID),
    PERSON_ID UUID REFERENCES PERSON(PERSON_ID)
);
CREATE TABLE CONTACT
(
    CONTACT_ID UUID PRIMARY KEY,
    CONTACT_VALUE VARCHAR(50),
    CONTACT_TYPE_ID UUID REFERENCES CONTACT_TYPE(CONTACT_TYPE_ID),
    PERSON_ID UUID REFERENCES PERSON(PERSON_ID)
);
CREATE TABLE DOCUMENTS
(
    DOCUMENTS_ID UUID PRIMARY KEY,
    DOCUMENTS_VALUE VARCHAR(50),
    DOCUMENT_TYPE_ID UUID REFERENCES DOCUMENT_TYPE(DOCUMENT_TYPE_ID),
    PERSON_ID UUID REFERENCES PERSON(PERSON_ID)
);
